CROPPED_IMAGE_SIZE = (54, 140)
ORIGINAL_IMAGES_DIRECTORY = 'leftImg8bit_trainvaltest'
COLORED_IMAGES_DIRECTORY = "gtFine"
ORIGINAL_IMAGE_SUFFIX = "_leftImg8bit"
COLORED_IMAGE_SUFFIX = "_gtFine_color"
